export {default as Loader} from './Loader'
export {default as Footer} from './Footer'
export {default as Services} from './Services'
export {default as Welcome} from './Welcome'
export {default as Transations} from './Transations'
export {default as NavBar} from './NavBar'